export const RESTORE_TOKEN = 'RESTORE_TOKEN'
export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_HEALTH_CARD_API = 'SET_HEALTH_CARD_API'