export default {
  //PREF
  PREF_TOKEN: "token",
  PREF_USER_ID: "user_id",
  PREF_USER_INFO: "user_info",
  PREF_USER_EMAIL: "email",
  PREF_ACCESS_TOKEN: "access_token",
  PREF_USER_NAME: "name",

  //APIs List
  API_BASE_URL: "http://upstaging.uptrust.in/api/",
  // API_BASE_URL: "https://uptrust.in/api/",
  API_SEND_OTP_WITH_EMAIL: "sendOTPwithemail",
  API_VERIFY_OTP_WITH_EMAIL: "verifyOTPwithemail",
  API_VERIFY_OTP_WITH_PHONE: "phoneverify",
  API_GET_USER_DETAIL: "userdetail",
  API_CLAIM: "claim",
  API_GET_CLAIMLIST: "claimlist",
  API_ADD_INQUIRY: "add_inquiry",
  API_ADD_REQUEST_CARD_PDF: "add_request_cardPDF",
  API_INQUIRY_LIST: "inquirylist",
  API_SEND_OTP_WITH_Phone: "sendOTPwithphone",
  API_VERIFY_OTP: "verifyOTP",
  API_ADD_QUOTE: "add_quote",
  API_GET_REMINDER: "get_reminder",
  API_SEND_REMINDERS: "send_reminder",
  API_LOGOUT: "logout",
  API_GET_NOTIFICATIONS: "notificationlist",

  // API_LOGIN: "check-user-login",
  // API_ASSET_BALANCE: "wallet-asset-balance",
  // API_TRANSACTION_DETAIL: "external/wallet-transactions",
  // API_WALLET_TRANSFER: "external/token-transfer",
  // API_REGISTER: "register-user",
  // API_GET_USER_LIST: "get-users-list",

  API_GET_HEALTH_CARDS: "userdetail",

  //PARAM
  PARAM_PHONE_NO: "phone",
  PARAM_USER_NAME: "username",
  PARAM_PASSWORD: "password",
  PARAM_OTP: "otp",
  PARAM_USER_ID: "user_id",
  PARAM_ACCESS_TOKEN: "access_token",
  PARAM_CARD_NO: "card_no",
  PARAM_DOCTOR_NAME: "doctor_name",
  PARAM_HOSPITAL_NAME: "hospital_name",
  PARAM_DIAGNOSIS: "diagnosis",
  PARAM_ADMISSION_DATE: "admission_date",
  PARAM_MOBILE_NO: "mobile_no",
  PARAM_EMAIL: "email",
  PARAM_POLICY_NO: "policy_no",
  PARAM_SUMMARY: "summary",
  PARAM_IS_PHONE_VERIFIED: "verified_phone",
  PARAM_IS_EMAIL_VERIFIED: "verified_email",
  PARAM_FCM_TOKEN: "device_token",
  PARAM_FULL_NAME: "full_name",

  //Constant Value
  APP_ID: "xx12tobp12xxx",
  ACCESS_TOKEN: "1234567890qwertyuiop",
  MERCHANT: "1Gw5xy4ewkx3arnnFR4HZk7v7QyjvSm1eZ1UWF",
  USER_ROLE: "user",
  FROM_MOBILE: "MOBILE",

  //Message
  NO_DATA_FOUND: "Data not available.",
  NO_INTERNET: "Please check your internet connection and try again.",
  OTP_RESEND_MSG: "Otp sent successfully.",
  POWEREDBY: "©Techforce 2022. All rights reserved.",
};
